debian: patches: add patch and update series
radxa-pkg/r8125-dkms pull request #7
Opened 2024-07-15 12:03 UTC by RadxaMitchell

Add patch to r8125 driver to get led light configurations from dts and adding patch names to series. This patch is from istoreos/istoreos@52313c5
Author: jjm2473 <jjm2473@gmail.com>

2024-07-15 12:18 UTC, RadxaYuntian commented
别老是关PR了，要修改直接强推你的分支就好

2024-07-15 12:20 UTC, RadxaYuntian requested changes

2024-07-15 12:20 UTC, RadxaYuntian commented on debian/patches/add-getting-led-configuration-from-dts.patch
> ++        u32 led_data[4];
```suggestion
+        u16 led_data[4];
```
和of_property_read_u16_array的变量类型保持一致

2024-07-16 01:26 UTC, RadxaMitchell commented
> 别老是关PR了，要修改直接强推你的分支就好

不小心关掉了，*-*

2024-07-16 03:10 UTC, RadxaYuntian requested changes
squash

2024-07-17 06:35 UTC, RadxaYuntian approved these changes

2024-07-17 06:38 UTC, merged